### ISSUE TITLE
Build new docker image

### ISSUE THREAD

**Issue by ewoks** [docToolchain/docker-image#12]
As few new features recently landed to docToolchain project (after version 1.2.0), it would be good to build & publish new dockerimage of the newest version to be able to take full advantage of the new features

1. tag new docToolchain version
2. build new docker image
3. publish new docker image to docker.hub

**Comment by ewoks** [comment]
cc: @rdmueller could you update dockerfile with the tag of the newest version after [#458](https://github.com/docToolchain/docToolchain/pull/458) is merged to the master?

**Comment by rdmueller** [comment]
Hi Vladi, there was some progress the last days regarding the docker images. We now have a v2.0.0-rc3

**Comment by ewoks** [comment]
Great 👏
I see rc4 is already there too... Got caught in a everyday job, but I will give it a spin anytime soon

**Comment by rdmueller** [comment]
I guess we can close this, can't we?
