### ISSUE TITLE
docker container should already contain all dependencies

### ISSUE THREAD

**Issue by rdmueller** [docToolchain/docker-image#15]
let's force gradle to prefetch all dependencies:

https://gist.github.com/matthiasbalke/3c9ecccbea1d460ee4c3fbc5843ede4a

**Comment by rdmueller** [comment]
it seems that a `./gradlew dependencies` should be enough to fetch all dependencies

**Comment by rdmueller** [comment]
ok, `dependencies` is not enough. We'll have to find another way.
see also https://stackoverflow.com/questions/28436473

**Comment by rdmueller** [comment]
just added this solution:
https://stackoverflow.com/questions/47102615/how-to-make-gradle-download-dependencies-without-actually-building-things

let's see how it works out

**Comment by ascheman** [comment]
To me it seems to be working now. Should we close this issue until we get more hints where it is still problematic, @rdmueller?

**Comment by rdmueller** [comment]
Yes, lets close this!
