### ISSUE TITLE
Release for Version 2.1.0

### ISSUE THREAD

**Issue by obue** [docToolchain/docker-image#36]
Hi @rdmueller,
can you please release a new docker image based on the august release as docker image?

**Comment by rdmueller** [comment]
Sorty, I missed to release the proper instructions. We switches the dockerhub org from rdmueller to doctoolchain. So, the 2.1.0 image can be found at doctoolchain/doctoolchain:2.1.0

This should also alread be redlexted in the current dtcw

**Comment by obue** [comment]
Okay I found https://hub.docker.com/r/doctoolchain/doctoolchain/tags. I will close this issue, but I highly recommend to add a Link in Github or a even additional a static link in the Github release to the new docker page.
