### ISSUE TITLE
New releases are no longer published as release?

### ISSUE THREAD

**Issue by delgurth** [docToolchain/docker-image#40]
It seems that the recent docker-image releases for docToolchain are no longer published on this GitHub repository as releases. The v2.2.0 and v2.1.0 also seem to have been skipped in this repo, but do exist on docker hub:

https://hub.docker.com/r/doctoolchain/doctoolchain/tags

Guess this has something to do with the change from rdmuller to doctoolchain as base?

https://github.com/docToolchain/docker-image/commit/df6723e333f722dc60fce83ef8a3c8a837026d5e

**Comment by rdmueller** [comment]
ah! Good Point.

In the past, the images where build on the docker hub. This workflow needed releases in this repository. The release was only a vehicle to start the build process.

Then the dockerhub started to charge for the builds, so I started to build and push them manually. This was to error prone, so we setup a github action. All of this didn't require the release in this repository anymore.

doctoolchain is now a sponsored open source project on dockerhub. So, build would be free of charge again, but I guess we will stick to the github actions.

Is this a problem? Should we create realeases over here again?

**Comment by delgurth** [comment]
For me this is not really a problem. With the organisation change & the releases not showing up on this GitHub page, it took me some time to find out that v2.2.0 was published. And now it looks like you have no new releases of the docker image. Perhaps add a release that says that the docker image now follows the releases of the main repository automatically?

Oh and the README.md still links to the rdmueller tags.

**Comment by rdmueller** [comment]
Thanx for the value feedback. These are good ideas!

**Comment by rdmueller** [comment]
implemented :-)
