### ISSUE TITLE
Question: pandoc support

### ISSUE THREAD

**Issue by ko** [docToolchain/docker-image#6]
I see that packages for pandoc in alpine were added to the Dockerfile but commented out. Is there any rationale as to why this is the case? Unofficial support? Preference to download and install from `cabal`? Forgot to uncomment? 

For context, I recently learned that I also need to generate `.docx` output for some documents, so I've been looking down that dependency tree lately. It would be great to continue to use this docToolchain docker image for all related workflows.

**Comment by rdmueller** [comment]
I think I wanted to keep the container small. 
Feel free to give it a try!

**Comment by ko** [comment]
I tried uncommenting and building this a few days ago. The docker image size ended up at 806MB.[0] I was also exploring a way to build `pandoc` from `cabal` because that would be more predictable (vs. a third-party repo), but that ended up with an image over 2.5 GB.[1] 

On the bright side, I was able to build a `.docx` after that change. 

If the size delta is acceptable, I think it would be valuable to have a more flexible docker image that increases the convenience and removes any potential activation energy. 

If the size delta is unacceptable, then a second docker image with a differentiating tag may be one avenue to mitigate some of those related issues.

[0] 
```
REPOSITORY                       TAG                 IMAGE ID            CREATED             SIZE
local.test.pandoc                latest              c77059ec4c7c        3 days ago          806MB
<none>                           <none>              f21ad0dc0221        4 days ago          2.51GB
rdmueller/doctoolchain           v1.1.0              bf8d4f678a5e        2 months ago        676MB
```

[1] There's probably a way to use multi-stage Docker images to build and extract the final bits for the production docker image, but that's a bit more exhaustive.

**Comment by rdmueller** [comment]
wouldn't it make sense to create a new image for pandoc which build on the old one? I think this would be the best solution...

**Comment by ko** [comment]
You're absolutely right. I was overthinking it.

How do you want to go about delivering a pandoc-capable Docker image? I think it would be reasonable if you were to host the image alongside your existing doctoolchain image on Docker Hub. I'm still a bit unclear about any CI/CD process that is currently setup, though.

**Comment by rdmueller** [comment]
regarding the CI/CD process: I used the autobuild functaionality on dockerhub:
https://docs.docker.com/docker-hub/builds/

It seems to build whenever a tag is created...

I think we have to setup a new autobuild for a second image on dockerhub...

**Comment by rdmueller** [comment]
If you have a docker ID, I could add you as collaborator to the repository...

**Comment by ko** [comment]
Apologies for dropping off. If you're still open, my Docker ID is `kennethko`.

**Comment by dr460neye** [comment]
Do you know if we have licensing conflicts when we move a copy of pandoc to this container?

Such a step could work:

```
FROM groovy:jre8
ENV LANG=C.UTF-8
ENV LC_CTYPE=en_US.UTF-8
USER root
RUN echo "add needed tools" \
    &&     apt-get update \
    &&     apt-get -y install curl wget zip unzip git bash graphviz python python-pip ruby  ttf-dejavu libgmp-dev libffi-dev lua5.3 lua5.3-lpeg \
    &&     pip install Pygments \
    &&     gem install rdoc --no-document \
    &&     gem install pygments.rb

COPY --from=pandoc/core:latest /usr/bin/pandoc* /usr/bin/

RUN git clone https://github.com/docToolchain/docToolchain.git \
    &&         cd docToolchain \
    &&         git checkout ${TAG} \
    &&         git submodule update -i \
    &&         ./gradlew tasks \
    &&         ./gradlew \
    &&         PATH="/docToolchain/bin:${PATH}"
RUN mkdir /project
WORKDIR /project
ENTRYPOINT ["/bin/bash"]

```

**Comment by rdmueller** [comment]
sorry, this issue is now quite old and I would love to see it fixed. Would be great if you could help me to make any progress.

**Comment by abellmann** [comment]
I created a Dockerfile, that adds pandoc support. I needed to upgrade the java version, though (not sure if this works for all use cases). See https://github.com/abellmann/doctoolchain-docker-image/blob/master/alpine/Dockerfile

**Comment by abellmann** [comment]
On dockerhub, this version is at https://hub.docker.com/r/abellmann/doctoolchain

**Comment by rdmueller** [comment]
@abellmann that is great! I wonder if we could create such an image which is build on top of the standard docToolchain container?

AFAIK, pandoc will add quite some mega bytes. If it is build on top of the standard image, I guess people could decide to maybe start with the smaller image and later just add the additional layer.

What do you think?

and btw - is it ok for you if I fork your project to the docToolchain organization?

**Comment by abellmann** [comment]
we could also create a separate base image for jdk15 and tag and build it separately to keep the java 8 version. the pandoc version would then be based of the jdk15 version

**Comment by rdmueller** [comment]
oh, haven't seen that yours is a fork :-) would jdk14 also be ok? Currently we don't test jdk15. But we could change this.
I think, as long as docToolchain works, the jdk version inside the container doesn't matter.

**Comment by abellmann** [comment]
I tried this with jdk 14 and it works, if we use pandoc 2.9. Higher versions of pandoc use a different alpine version, that uses newer libraries for libffi resulting in an unusable pandoc version in doctoolchain..

**Comment by abellmann** [comment]
If I create a  pull request should we upgrade the existing docker image to jdk14 or create a new dockerfile for this?

**Comment by abellmann** [comment]
Can we add the doctoolchain with pandoc as a separate directory in this repository (i.e. alpine-pandoc/Dockerfile)

**Comment by abellmann** [comment]
I already prepared the next pull request, that will add the pandoc support. Since this depends on the new java version, I will create this after the java upgrade was tagged and build. (see https://github.com/abellmann/doctoolchain-docker-image/blob/pandoc-support/alpine-pandoc/Dockerfile).

**Comment by abellmann** [comment]
@rdmueller : does this work for you?

**Comment by rdmueller** [comment]
Great! Let's take a look at the new PR!

So, we will then have an `alpine` and an `alpine-pandoc` version. That's cool! And everything with a new JDK.
I love it!

**Comment by abellmann** [comment]
@rdmueller :  Can you tag and build the new image? I will create the new PR for pandoc. The image version for the base image will still be missing in the PR. We could then fix the version in a separate commit or PR.

**Comment by abellmann** [comment]
@rdmueller : ping..

**Comment by rdmueller** [comment]
pong. 😉
sorry, I hope to find some time during easter.
it is quite important for me to make progress with the docker images...

**Comment by rdmueller** [comment]
OK. I now have to figure out how to build both images through the docker hub from one repository...

**Comment by rdmueller** [comment]
I think I created and triggered a build. let's see: https://hub.docker.com/repository/docker/rdmueller/doctoolchain-pandoc/builds

**Comment by rdmueller** [comment]
didn't mean to close this issue.

I still have problems with the build. I had to specify a specific version in the `FROM`statement. And now I get this:

```
Starting build of index.docker.io/rdmueller/doctoolchain-pandoc:v1.3.1-p2...
Step 1/7 : FROM rdmueller/doctoolchain:v1.3.1
---> b86c36c0f93a
Step 2/7 : RUN apk --no-cache add gmp libffi lua5.3 lua5.3-lpeg
---> Running in 182f68fab674
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/community/x86_64/APKINDEX.tar.gz
(1/4) Installing linenoise (1.0-r1)
(2/4) Installing lua5.3-libs (5.3.5-r2)
(3/4) Installing lua5.3 (5.3.5-r2)
(4/4) Installing lua5.3-lpeg (1.0.1-r4)
Executing busybox-1.29.3-r10.trigger
OK: 281 MiB in 106 packages
Removing intermediate container 182f68fab674
---> aecccc329b75
Step 3/7 : COPY --from=pandoc/core:2.9 /usr/bin/pandoc /usr/bin/pandoc-citeproc /usr/bin
When using COPY with more than one source file, the destination must be a directory and end with a /
```

**Comment by rdmueller** [comment]
Success! https://hub.docker.com/repository/docker/rdmueller/doctoolchain-pandoc/tags?page=1&ordering=last_updated

So, if this image works, we can now build pandoc images!

**Comment by rdmueller** [comment]
hm. do the lincenses match? Are we allowed to create such a container?

**Comment by rdmueller** [comment]
image seems to work:

```
docker run -it rdmueller/doctoolchain:rc-1.2.0
> pandoc -h
```

**Comment by ehmkah** [comment]
pandoc should be now available - https://hub.docker.com/r/doctoolchain/doctoolchain-with-pandoc

**Comment by rdmueller** [comment]
embarrassing how old this issue is. But I think we can close it now...
