### ISSUE TITLE
:generateHTML NO-SOURCE

### ISSUE THREAD

**Issue by feinstaub** [docToolchain/docker-image#8]
Build reports "successful", but no result files:
```
 ~/d/d/doc > doctoolchain.sh generateHTML                                                                                                                                     10.2s  Fr 26 Jul 2019 11:20:09 CEST
Starting a Gradle Daemon, 1 incompatible and 1 stopped Daemons could not be reused, use --status for details
:generateHTML NO-SOURCE

BUILD SUCCESSFUL in 8s
```

with doctoolchain.sh:
```
#!/usr/bin/env bash
#CONFIG=config/docToolchain.groovy
CONFIG=Config.groovy
docker run --rm -it --entrypoint /bin/bash -v ${PWD}:/project rdmueller/doctoolchain:v1.1.0 \
-c "doctoolchain . $1 $2 $3 $4 $5 $6 $7 $8 $9 -PmainConfigFile=$CONFIG && exit"
```
In contrast, when I start docToolchain from a local installation, it works:

```
cd /home/gm/dev/docToolchain/bin/ ; ./doctoolchain /home/gm/dev/docToolchain_sample/doc generateHTML

> Configure project :
index.adoc

> Task :generateHTML
unsupported Java version "11", defaulting to 1.7
Converting /home/gm/dev/docToolchain_sample/doc/index.adoc

BUILD SUCCESSFUL in 5s
1 actionable task: 1 executed
```

**Comment by rdmueller** [comment]
can you please start it with the '--info' parameter. This should show which config is picked up...

**Comment by feinstaub** [comment]
Thanks for the hint. With that, I could change the structure to this:
* project_root/
    * src/
       * docs/
           * Config.groovy

and run the docker script from working dir project_root.

**Comment by rdmueller** [comment]
hm. ist seems that you found a situation where the wrong config is picked up. I think we should fix this...

**Comment by sabatmonk** [comment]
i have this exact issue, what was the solution in the end, i only have one config file so it should be the one used...
