### ISSUE TITLE
publishToConfluence does not respect preambleTitle

### ISSUE THREAD

**Issue by azngeek** [docToolchain/docker-image#9]
I changed the title to something else like "Architecture". Instead it still uses arc42. 

```
confluence.with {
    input = [[ file: "build/html5/arc42-template.html", ancestorId: "46956627" ]]
    api = 'https://wiki.abc.de/rest/api/'
    spaceKey = 'ABC'
    createSubpages = false
    preambleTitle = 'Architektur' // This should be used
    pagePrefix = ''
    pageSuffix = ''
    credentials = "test:test".bytes.encodeBase64().toString()
    extraPageContent = 'test'
}

```

This is how i mount it 

```
#!/usr/bin/env bash
#CONFIG=config/docToolchain.groovy
docker run --rm -it --entrypoint /bin/bash -v /home/user/projects/test/volume/htdocs:/project rdmueller/doctoolchain:v1.1.0 \
-c "doctoolchain . publishToConfluence --info -PmainConfigFile=./docs/Config.groovy -PinputPath=./docs && exit"
```

And this is the output from the cli

Putting task artifact state for task ':publishToConfluence' into context took 0.001 secs.
Up-to-date check for task ':publishToConfluence' took 0.0 secs. It is not up-to-date because:
  Task has not declared any outputs.
docToolchain> docDir: /project
publish /project/build/html5/arc42-template.html
arc42

**Comment by rdmueller** [comment]
hm. I guess that is a problem with docToolchain itself, not the container...

**Comment by rdmueller** [comment]
let's continue this over at docToolchain: github.com/docToolchain/docToolchain/issues/398
